name: edlife_ccu_frontend
description: Frontend-only Flutter app replicating EDlife CCU Figma design
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.3
  flutter_svg: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPro/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPro/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPro/SFPRODISPLAYBOLD.OTF
          weight: 700
